Module Module6
    'Arlo Russell
    'Exercise 6
    '9/18/23

    Sub Main()
        Console.WriteLine("Arlo Russell" & vbNewLine)

        Console.Write("Knock, knock")
        Console.ReadLine()
        Console.Write("Who's There?")
        Console.ReadLine()
        Console.Write("Nobel.")
        Console.ReadLine()
        Console.Write("Nobel who?")
        Console.ReadLine()
        Console.WriteLine("Nobel...that's why I knocked.")
        Console.ReadLine()
        Console.Write("Knock, knock")
        Console.ReadLine()
        Console.Write("Who's there?")
        Console.ReadLine()
        Console.Write("Tank.")
        Console.ReadLine()
        Console.Write("Tank who?")
        Console.ReadLine()
        Console.WriteLine("You're Welcome")
        Console.ReadLine()
        Console.Write("Knock, knock")
        Console.ReadLine()
        Console.Write("Who's there?")
        Console.ReadLine()
        Console.Write("Luke")
        Console.ReadLine()
        Console.Write("Luke who?")
        Console.ReadLine()
        Console.WriteLine("Luke through the peep hole and find out.")
        Console.ReadLine()
        Console.Write("Knock, knock")
        Console.ReadLine()
        Console.Write("Who's there?")
        Console.ReadLine()
        Console.Write("Figs")
        Console.ReadLine()
        Console.Write("Figs who?")
        Console.ReadLine()
        Console.WriteLine("Figs the doorbell, it's not working")
        Console.ReadLine()
        Console.Write("Knock, knock")
        Console.ReadLine()
        Console.Write("Who's there?")
        Console.ReadLine()
        Console.Write("Hal")
        Console.ReadLine()
        Console.Write("Hal who?")
        Console.ReadLine()
        Console.WriteLine("Hal will you know if you don't open the door?")

        Console.ReadKey()

    End Sub
End Module
